### ISSUE TITLE
Challenge Files Do Not Download

### ISSUE THREAD

**Issue by PMVamsi** [p0dalirius/ctfd-parser#3]
```
connection_info = chall_json["connection_info"]
if len(connection_info) != 0:
    f.write("%s\n\n" % connection_info)
```

The second line above causes an exception and challenge files do not download. This seems to happen when connection_info == None.

Changed it to 
`if connection_info != None and len(connection_info) != 0:`

**Comment by p0dalirius** [comment]
Fixed.
