### ISSUE TITLE
Enhancement Request: Support Cloudflare

### ISSUE THREAD

**Issue by PMVamsi** [p0dalirius/ctfd-parser#5]
I believe challenges hosted behind Cloudflare don't work currently. Here is an example:
https://ctf.heroctf.fr/

**Comment by p0dalirius** [comment]
Hi,

It works fine:

![image](https://user-images.githubusercontent.com/79218792/170828795-003ae136-a64a-491d-bf15-b5ad44ef296f.png)

Best regards,
