### ISSUE TITLE
[bug] File download issue

### ISSUE THREAD

**Issue by C3n7ral051nt4g3ncy** [p0dalirius/ctfd-parser#7]
When parsing `https://osintgames.ctfd.io`, I get all the questions in `.md` files, but `no photos` or `videos` were pulled.

<img width="767"  src="https://user-images.githubusercontent.com/104733166/185746566-f772acd6-bc06-467d-abb9-bbdc86992088.png">

**Comment by eybisi** [comment]
https://github.com/p0dalirius/ctfd-parser/blob/master/ctfd_parser.py#L119
returns 403 for some ctfd panels.
